import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import List from "./list/page";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <img src="/images/logo.png" alt="Logo South Park" />
          <h2>Laboratoire 3</h2>
        </header>

        <nav>
          <Link href="/">Accueil</Link>
          <Link href="/list">Liste de personnages</Link>
          <Link href="/details">Fiche détaillée</Link>
        </nav>

        <main>
          {children}
          
        </main>

        <footer>
          <div>&copy;Tous droits réservés à South Park</div>
        </footer>
      </body>
    </html>
  );
}
